### ISSUE TITLE
Is possible adding compatibility with Wayland?

### ISSUE THREAD

**Issue by q2dg** [keszybz/typoenforcer#2]
Thanks!

**Comment by keszybz** [comment]
I would love that, but I don't think it's possible. One of the main points of wayland is that one process cannot just write to the window of another process. But maybe this could be done in some other manner, e.g. through the pty layer.

**Comment by q2dg** [comment]
Thanks a lot. I understand.
I'll close the issue, then, if you don't mind.

**Comment by ownby1999** [comment]
Thanks
